config/routes.rb
Rails.application.routes.draw do

  resources :campaigns
  resources :users
  resources :search

  get 'import_camp', to: 'campaigns#index'
  get 'search_auto', to: 'search#auto_search'
  get 'last_auto_search', to: 'search#last_auto_search'

  root 'search#index'

end

app/models/campaign.rb
class Campaign
  include ActiveModel::Model

  # This are the campaigns that are uploaded by the user
  @@loaded_campaigns = {}

  ######################################################################
  # This variables are use every time a matching (user-campaigns) is run
  # The objective of this is store the last result
  # so it can be show to the user interested
  # to know ho the last result when
  ######################################################################
  @@used_user = {}
  @@used_campaigns = []
  @@highest_price = {}
  @@targeted_user = []
  @@last_diff = nil

  ###################
  # Setters & Getters
  ###################
  def value
    @@loaded_campaigns
  end

  def value=(value)
    @@loaded_campaigns = value
  end

  def used_user
    @@used_user
  end

  def used_user=(value)
    @@used_user = value
  end

  def used_campaigns
    @@used_campaigns
  end

  def used_campaigns=(value)
    @@used_campaigns = value
  end

  def highest_price
    @@highest_price
  end

  def highest_price=(value)
    @@highest_price = value
  end

  def targeted_user
    @@targeted_user
  end

  def targeted_user=(value)
    @@targeted_user = value
  end

  def last_diff
    @@last_diff
  end

  def last_diff=(value)
    @@last_diff = value
  end

  # Set the Json file in the server memory
  def set_json_file(file)
    file_content = file.read

    hash = JSON.parse file_content

    self.value = hash
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  # Variables of instance, these are not store in DB, they are here to help in the manual search
  attr_accessor :name, :a, :b, :c

  # Define the array of letters we are going to use in the generation of attributes for each user
  ALPHABET = ("A".."Z").to_a

  # It generates automatically an user with all its attributes,
  # according to the counter of request to the generate user API
  def generate_user

    user = User.first

    # If the user does not exist then create a new one
    if user.blank?
      user = User.create!(counter: 0)
    end

    # Increment the counter for every request made to the api
    count = User.increment_counter(:counter, user)

    # Set this class varible update with the value in DB
    user.counter += count

    {
        user: "u#{user.counter}",
        profile: generate_profile(user.counter)
    }
  end

  # Generate the profile attr base on the alphabet length
  def generate_profile(counter)
    profiles = counter % 26
    if profiles == 0
      if counter > 0
        profiles = 26
      else
        profiles = 1
      end
    end

    attributes = Hash.new

    (1..profiles).map do |i|
      attributes["attr_#{User::ALPHABET[i-1]}"] = "#{User::ALPHABET[i-1]}#{rand(1..200)}"
    end

    # Return the profile attributes
    attributes
  end

  # Generates a user base on whet the user passes as parameters
  def generate_manual_user(user)
    {
        user: user.name,
        profile: generate_manual_profile(user)
    }
  end

  # Very small profile hash, just to show how it works the manual user creation
  def generate_manual_profile(user)
    profile = {}
    profile["attr_A"] = user.a if !user.a.blank?
    profile["attr_B"] = user.b if !user.b.blank?
    profile["attr_C"] = user.c if !user.c.blank?
    profile
  end

  # If all targets of the campaign can be found in a user's profile, then this user is called “Targeted User”.
  def targeted_user(campaigns, user)
    # Start taking time 
    start = Time.now

    targeted_user = []
    highest_price = {}

    campaigns.each do |campaign|

      is_it_targeted = is_it_targeted?(campaign, user)

      if is_it_targeted
        targeted_user << campaign

        if highest_price.blank?
          highest_price = campaign
        else
          highest_price = campaign if campaign["price"] > highest_price["price"]
        end
      end
    end

    finish = Time.now
    diff = ((finish - start)*1000).round(5)

    campaign = Campaign.new

    campaign.used_user = user
    campaign.used_campaigns = campaigns
    campaign.highest_price = highest_price
    campaign.targeted_user = targeted_user
    campaign.last_diff = diff

    # Return targeted_users
    highest_price
  end

  # Checks individual campaigns if all targets of the campaign can be found in an user's profile
  # and the user’s profile attribute value can be found in the list of the campaign target attr_list
  def is_it_targeted?(campaign, user)
    is_it_targeted = true
    campaign["target_list"].each do |target|
      target_attr =  target["target"]
      if user[:profile][target_attr].nil?
        is_it_targeted = false
        break
      end

      user_max_target = user[:profile][target_attr][1, user[:profile][target_attr].size-1].to_i
      campaign_max_target = target["attr_list"].last[1, target["attr_list"].last.size-1].to_i

      if user_max_target > campaign_max_target
        is_it_targeted = false
        break
      end
    end
    is_it_targeted
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  # Sets the variables to use in the view
  def index
    @campaign = Campaign.new
  end

  # Handles the importation of the campaigns json file
  def create
    uploaded_file = params[:file]

    # Set the Json file in the server memory
    @campaign = Campaign.new.set_json_file(uploaded_file)

    redirect_to import_camp_path
  rescue
    redirect_to import_camp_path, flash: { danger: "You have to choose a valid json file" }
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  # Sets the variables to use in the view
  def index
      @user = User.new

      @campaigns = Campaign.new.value
  end

  # Does the matching with the campaign file in memory with the user store in the db
  # process it and then returns a json value to the view
  def auto_search

    # If there is no campaigns json file return the user to a path where the user can upload one
    if Campaign.new.value.blank?
      redirect_to campaigns_path, flash: { danger: "First there has to be a json file define" }
    else
      campaigns = Campaign.new.value
      user = User.first.generate_user
      highest_price = User.new.targeted_user(campaigns, user)

      # If the highest price is null then show 'none' otherwise show the highest price campaign
      render json: highest_price['campaign_name'].nil? ? 'none' : highest_price['campaign_name']
    end
  end

  # Sets the variables to the view of last used values and results
  def last_auto_search
    campaign = Campaign.new

    @used_user = campaign.used_user
    @used_campaigns = campaign.used_campaigns
    @highest_price = campaign.highest_price
    @targeted_user = campaign.targeted_user
    @last_diff = campaign.last_diff
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # Generate the user with the counter the it has
    render json: User.new.generate_user
  end

  # Handles the manual user creation
  def create
    if Campaign.new.value.blank?
      redirect_to campaigns_path, flash: { danger: "First there has to be a json file define" }
    else
      # Set the params from the view
      user = User.new(name: params[:user]["name"], a: params[:user]["a"], b: params[:user]["b"], c: params[:user]["c"])

      generated_user = @user.generate_manual_user(user)
      campaigns = Campaign.new.value

      # Launch the matching with the campaigns in memory and the user pass in the params
      User.new.targeted_user(campaigns, generated_user)

      # Go and see the result of this manual search
      redirect_to last_auto_search_path
    end
  rescue
    redirect_to import_camp_path, flash: { danger: "You have to choose a valid json file" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/campaigns/index.html.erb
<div class="row">
  <div class="col-md-6">
<%= form_tag @campaign, :multipart => true do %>
    <label for="file">Upload text File</label> <%= file_field_tag "file", class: 'btn btn-default btn-file' %>
    <%= submit_tag 'submit', class: 'btn btn-default' %>
<% end %>
  </div>
  <div class="col-md-5 info instructions">
    <h4>Do you want to generate another json file?</h4>
    <br>
    Go Here <%= link_to 'Here', 'https://mogamescampaigns.herokuapp.com/campaigns?x=50&y=10&z=1000', target: :blank %>
    <br>
    Remember to change Attrs 'X', 'Y' and 'Z' according to what you want, then right click on the document and save as,
    give it a nice cool name and then come back here and test it out!
  </div>
</div>

<h1>Current Campaigns file loaded</h1>
<pre id="result">
  <%= JSON.pretty_generate(@campaign.value) %>
</pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Performance Test Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Juan Sebastian Velez</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if params[:controller] == 'campaigns' %>">
          <%= link_to 'Import Campaign File', import_camp_path %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'search' && params[:action] == 'index' %>">
          <%= link_to 'Manual Search', search_index_path %>
        </li>
        <li>
          <%= link_to 'Do the Auto Search', search_auto_path, target: :blank %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'search' && params[:action] == 'last_auto_search' %>">
          <%= link_to 'Show last Auto Search Result', last_auto_search_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |name, msg| %>

      <%= content_tag(:div, content_tag(:a, 'X', 'data-dismiss': "alert", class: "close") + msg, class: "alert alert-#{name}") %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/search/index.html.erb
<div class="row">
  <%= simple_form_for  @user do |f| %>
      <%= f.input :name, autofocus: true %>
      <%= f.input :a, label: 'attr_A', placeholder: 'Axx, example A13, if this is not present then it will be ignore' %>
      <%= f.input :b, label: 'attr_B', placeholder: 'Bxx, example B29, if this is not present then it will be ignore' %>
      <%= f.input :c, label: 'attr_C', placeholder: 'Cxx, example C6, if this is not present then it will be ignore' %>
      <%= f.button :submit, 'Do the search' %>
  <% end %>
</div>
<div class="row">
  <h1>This are the Campaigns to be use</h1>
  <% if @campaigns.blank? %>
      <div class="alert alert-danger">
        Before you can use this manual search you have to load a json file first, go load one
        <%= link_to 'Here', import_camp_path %>
      </div>
  <% else %>
  <span id="campaigns-url">
    Came from here <%= link_to 'Here', import_camp_path %>
</span>
  <% end %>
  <pre id="campaigns">
    <%= JSON.pretty_generate(@campaigns) %>
</pre>
</div>

app/views/search/last_auto_search.html.erb
<div class="col-md-5">

  <h1>This is the User used</h1>
  <span>
    Came from here <%= link_to 'user', users_path, target: '_blank' %>
  </span>
  <pre id="user">
    <%= JSON.pretty_generate(@used_user) %>
  </pre>

  <h1>This are the Campaigns used</h1>
  <span id="campaigns-url">
    Came from here <%= link_to 'Here', import_camp_path %>
  </span>
  <pre id="campaigns">
    <%= JSON.pretty_generate(@used_campaigns) %>
  </pre>
</div>

<div class="col-md-7">

  <span id="time">
    <%= "Time elapsed #{@last_diff} milliseconds" %>
  </span>

  <h1>This Campaign with the highest price</h1>
  <pre id="highest_price">
    <%= JSON.pretty_generate(@highest_price) %>
  </pre>

  <h1>This are the Targeted User </h1>
  <pre id="targeted_user">
    <%= JSON.pretty_generate(@targeted_user) %>
  </pre>

</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>